# Setup
title:               quantmuse
tagline:             'Musings of a buy-side quant'
description:         'Musings of a buy-side quant'
url:                 'https://quantmuse.net'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              quantmuse  
  email:             quantmuse@proton.me

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
